language: ruby
rvm:
  - 2.0.0
  - 1.9.3
  - 1.9.2
  - jruby-19mode
  - jruby-head
  - rbx
matrix:
  allow_failures:
    - rvm: rbx

gemfile:
  - Gemfile
  
# whitelist
branches:  
  only:
    - master